"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (1 / 10)
assert math.isclose(value, 0.1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '10 Hz 발행을 주기(초)로 바꾸기', "actual": value})
value = ((10 - 1) / 10)
assert math.isclose(value, 0.9, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '발행자 depth 10, 10 Hz에서 늦게 합류한 구독자가 받는 가장 오래된 표본의 나이(초)', "actual": value})
value = ((10 - 1) / 50)
assert math.isclose(value, 0.18, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '같은 depth 10을 50 Hz로 발행할 때 가장 오래된 표본의 나이(초): 발행률이 높을수록 같은 depth가 덮는 시간이 짧아진다', "actual": value})
value = (0.4 * 10 + 1)
assert math.isclose(value, 5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'lifespan 0.45초, 10 Hz에서 남는 표본 수: 0.45초를 넘지 않는 가장 큰 나이 0.4초까지 0, 0.1, 0.2, 0.3, 0.4초의 표본', "actual": value})
value = (10 - (0.4 * 10 + 1))
assert math.isclose(value, 5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'depth 10 가운데 lifespan 0.45초를 넘어 버려지는 표본 수', "actual": value})
value = (100 - (0.4 * 10 + 1))
assert math.isclose(value, 95, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '반례: depth를 100으로 늘려도 lifespan 0.45초라면 버려지는 표본 수만 늘어난다(남는 개수는 그대로 5)', "actual": value})
value = ((3 - 1) / 10)
assert math.isclose(value, 0.2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '경계: 구독자 쪽 keep last depth가 3이면 구독자 큐에 남는 가장 오래된 표본의 나이(초)', "actual": value})
value = (10 * 0)
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '경계: 발행자가 transient local이어도 구독자가 volatile이면 받는 과거 표본 수(원문 표: 새 메시지만 받음)', "actual": value})
value = (0.5 * 0.9)
assert math.isclose(value, 0.45, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '0.9초 전 상태를 받은 모니터 노드가 0.5 m/s로 이동 중인 로봇에 대해 보는 위치 차이(m)', "actual": value})
print(json.dumps(results, ensure_ascii=False))
