"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (1000 / 10)
assert math.isclose(value, 100, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '10 Hz 레이저의 발행 주기(ms)', "actual": value})
value = (500 / 100)
assert math.isclose(value, 5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'lease 500 ms 안에 들어가는 레이저 발행 주기 수', "actual": value})
value = (1000 - 500)
assert math.isclose(value, 500, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '구독자 요청 lease 1000 ms − publisher 제공 500 ms (0 이상이면 호환)', "actual": value})
value = (250 - 500)
assert math.isclose(value, -250, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '구독자 요청 lease 250 ms − publisher 제공 500 ms (음수면 비호환, 연결 없음)', "actual": value})
value = (500 - 1000 / 100)
assert math.isclose(value, 490, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'automatic 모드: lease 500 ms − 같은 노드 100 Hz IMU의 갱신 간격 (양수면 레이저 정지가 가려짐)', "actual": value})
value = (500 - 150)
assert math.isclose(value, 350, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'manual by topic 최악 감지 시간 500 ms − deadline 150 ms 감지 시간', "actual": value})
value = (80 - 100)
assert math.isclose(value, -20, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '경계 반례(레이저가 노드의 유일한 publisher, automatic 모드): lease 80 ms − 발행 주기 100 ms (음수면 정상 발행 중에도 매 주기 lease가 끊김)', "actual": value})
value = (3 * 100)
assert math.isclose(value, 300, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'lease를 발행 주기 3개로 잡을 때의 값(ms)', "actual": value})
print(json.dumps(results, ensure_ascii=False))
