"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (10 * 30 + 2 * 20)
assert math.isclose(value, 340, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '전체 작업공간 클린 빌드를 하나씩 처리한 합계(초): 의존 10개×30초 + 내 패키지 2개×20초', "actual": value})
value = (2 * 20)
assert math.isclose(value, 40, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '내 패키지 2개만 둔 overlay의 클린 빌드 합계(초)', "actual": value})
value = ((10 * 30 + 2 * 20) / (2 * 20))
assert math.isclose(value, 8.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '클린 빌드 합계 기준 전체 대비 overlay 배율', "actual": value})
value = ((10 * 340 - 10 * 40) / 60)
assert math.isclose(value, 50, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '상한 가정: 하루 10번 모두 클린 빌드할 때 overlay로 줄어드는 합계(분)', "actual": value})
value = (340 - 3 * 30)
assert math.isclose(value, 250, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'COLCON_IGNORE로 의존 패키지 3개를 뺀 클린 빌드 합계(초)', "actual": value})
value = (3 * 30)
assert math.isclose(value, 90, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'COLCON_IGNORE 3개가 하나씩 처리하는 합계에서 덜어내는 몫(초)', "actual": value})
value = (1 * 20)
assert math.isclose(value, 20, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '--symlink-install 없이 ament_python 패키지 A의 Python 파일만 고쳤을 때 반영을 위해 다시 빌드하는 시간(초)', "actual": value})
value = (0)
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '--symlink-install로 설치한 A에서 Python 파일만 고쳤을 때 반영을 위해 다시 빌드하는 시간(초)', "actual": value})
value = (20 * (1 - 0.25))
assert math.isclose(value, 15, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '테스트 비중 25% 가정에서 ament_cmake 패키지 B를 -DBUILD_TESTING=0으로 빌드한 시간(초)', "actual": value})
value = (0 + 20 * (1 - 0.25))
assert math.isclose(value, 15, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'overlay에서 A는 symlink로 처리하고 B만 테스트 없이 다시 빌드할 때의 합계(초)', "actual": value})
print(json.dumps(results, ensure_ascii=False))
