"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (0+4+4+0+4+4)
assert math.isclose(value, 16, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '같은 호스트 표에서 통신하는(O) 칸 수', "actual": value})
value = (0+2+3+0+4+4)
assert math.isclose(value, 13, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '다른 호스트 표에서 통신하는(O) 칸 수', "actual": value})
value = ((0+4+4+0+4+4)-(0+2+3+0+4+4))
assert math.isclose(value, 3, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '호스트를 나누면 X로 바뀌는 칸 수(모두 정적 피어 없는 LOCALHOST가 관여)', "actual": value})
value = ((0+2+3+0+4+4)/36)
assert math.isclose(value, 0.3611111111111111, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '다른 호스트에서 36칸 중 통신하는 비율', "actual": value})
value = ((0+0+0+0+0+0)+(0+0+0+0+0+0))
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '반례: A가 OFF인 두 행은 정적 피어가 있어도 다른 호스트 6열 모두 X', "actual": value})
value = (0+1+1+1)
assert math.isclose(value, 3, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '다른 호스트에서 A·B 모두 LOCALHOST인 4조합(피어 없음/있음 × 없음/있음) 중 O 개수: 한쪽만 정적 피어가 있어도 O', "actual": value})
value = (1+1+1+1)
assert math.isclose(value, 4, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '같은 호스트에서 A·B 모두 LOCALHOST인 4조합 중 O 개수', "actual": value})
value = (1+1+1+1)
assert math.isclose(value, 4, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '다른 호스트에서 A·B 모두 SUBNET인 4조합 중 O 개수(기본값 SUBNET끼리는 정적 피어 없이도 O)', "actual": value})
print(json.dumps(results, ensure_ascii=False))
