const assert = require('assert');
const {rest,retry,inventory} = require('../deploy/wordpress/huntlab-warm-editorial/assets/reader-tools.js');
const good={status:201,type:'application/json; charset=utf-8',body:'{"id":123,"status":"publish"}'};
assert.strictEqual(rest(good).ok,true);
assert.strictEqual(rest({...good,status:403}).ok,false);
assert.strictEqual(rest({...good,type:'text/html',body:'<html>login</html>'}).code,'type');
for(const body of ['null','[]','{"id":true}','{"id":-1}','{"id":0}','{"id":"123"}','{']) assert.strictEqual(rest({...good,body}).ok,false);
assert.strictEqual(rest({...good,expected:124}).code,'identity');
assert.strictEqual(rest({...good,body:'{"id":123,"status":"draft"}'}).code,'publication');
const now='2026-09-15T12:00:00Z';
assert.strictEqual(retry({retry:'120',now}).seconds,120);
assert.strictEqual(retry({retry:'Tue, 15 Sep 2026 12:00:07 GMT',now}).seconds,7);
assert.strictEqual(retry({retry:'Tue, 15 Sep 2026 11:00:07 GMT',now}).seconds,0);
for(const value of ['-1','1.2','NaN','tomorrow','Infinity','']) assert.strictEqual(retry({retry:value,now}).ok,false);
assert.strictEqual(retry({retry:'12',now:'2026-09-15T12:00:00'}).ok,false);
assert.strictEqual(inventory({total:3,perPage:2,ids:'1,2,3'}).ok,true);
assert.strictEqual(inventory({total:3,perPage:2,ids:'1,1,3'}).ok,false);
assert.strictEqual(inventory({total:119,perPage:100,ids:Array.from({length:100},(_,i)=>i+1).join(',')}).ok,false);
assert.strictEqual(inventory({total:0,perPage:100,ids:''}).ok,true);
assert.strictEqual(inventory({total:'',perPage:100,ids:''}).ok,false);
assert.strictEqual(inventory({total:1,perPage:100,ids:'NaN'}).ok,false);
console.log('Reader tools: response, retry and inventory edge cases passed');
