from pathlib import Path
import unittest

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
PLUGIN = ROOT / "deploy/wordpress/huntlab-warm-editorial"
CATEGORY_TABS = (
    ROOT / "deploy/wordpress/huntlab-category-tabs/huntlab-category-tabs.php"
)


class HuntLabWarmEditorialTests(unittest.TestCase):
    def test_plugin_loads_a_versioned_local_stylesheet(self):
        php = (PLUGIN / "huntlab-warm-editorial.php").read_text(encoding="utf-8")
        self.assertIn("Plugin Name: Hunt News Warm Editorial Theme", php)
        self.assertIn("wp_enqueue_style", php)
        self.assertIn("assets/warm-editorial.css", php)
        self.assertIn("filemtime", php)
        self.assertIn("huntlab-warm-editorial-late-overrides", php)
        self.assertIn("add_action( 'wp_head'", php)
        self.assertIn("huntlab_warm_editorial_home_intro", php)
        self.assertIn("WordPress 자동화 문제를", php)
        self.assertIn("Hunt News · 검증된 문제 해결 라이브러리", php)
        self.assertIn("코드와 테스트로 검증합니다", php)
        self.assertNotIn("30초 안에 파악하세요", php)
        self.assertNotIn("기술 뉴스를 읽고 남는 세 가지", php)
        self.assertNotIn('id="hunt-news-reading-guide"', php)
        self.assertIn("'label' => 'AI/ML 핵심'", php)
        self.assertIn("'label' => '국내 시사'", php)
        self.assertIn("Hunt News 콘텐츠 원칙", php)
        self.assertIn("hunt_news_translate_archive_labels", php)
        self.assertIn("hunt_news_remove_legacy_category_hero", php)
        self.assertIn("remove_action( 'kadence_hero_header', 'Kadence\\\\hero_title' )", php)
        self.assertIn("'Read More'       => '더 읽기'", php)
        self.assertIn("'Continue'        => '계속 읽기'", php)
        self.assertIn("'Page navigation' => '페이지 탐색'", php)
        self.assertIn("'Similar Posts'   => '비슷한 글'", php)
        self.assertIn("'Comment *'              => '댓글 *'", php)
        self.assertIn("is_home() || is_front_page() || is_category()", php)

    def test_palette_keeps_warm_surfaces_and_accessible_ink(self):
        css = (PLUGIN / "assets/warm-editorial.css").read_text(encoding="utf-8")
        self.assertIn("--huntlab-canvas: #f5efe6", css)
        self.assertIn("--huntlab-surface: #fffaf2", css)
        self.assertIn("--huntlab-ink: #292621", css)
        self.assertIn("--huntlab-terracotta: #a95f49", css)
        self.assertIn(".huntlab-category-tabs__link.is-active", css)
        self.assertIn(".huntlab-home-intro", css)
        self.assertIn(".hunt-news-reading-guide", css)
        self.assertIn(".hunt-news-category-grid", css)
        self.assertIn("@media (prefers-reduced-motion: reduce)", css)

    def test_code_blocks_keep_readable_text_and_horizontal_scroll(self):
        php = (PLUGIN / "huntlab-warm-editorial.php").read_text(encoding="utf-8")
        css = (PLUGIN / "assets/warm-editorial.css").read_text(encoding="utf-8")

        self.assertIn("Version: 7.0.0", php)
        self.assertIn(".single-content pre code", css)
        self.assertIn("color: #f7f3ea !important", css)
        self.assertIn("color: inherit !important", css)
        self.assertIn("overflow-x: auto", css)
        self.assertIn("white-space: pre", css)
        self.assertIn(".menu-toggle-open", css)
        self.assertNotIn(".menu-toggle-open-container .menu-toggle-open", css)

    def test_briefing_glass_effect_stays_on_navigation_and_emphasis_surfaces(self):
        php = (PLUGIN / "huntlab-warm-editorial.php").read_text(encoding="utf-8")
        css = (PLUGIN / "assets/warm-editorial.css").read_text(encoding="utf-8")

        self.assertIn("--hunt-brief-glass-light", css)
        self.assertIn("body.home #masthead {\n\t-webkit-backdrop-filter", css)
        self.assertIn(".hunt-news-date-nav {\n\talign-self: start;\n\t-webkit-backdrop-filter", css)
        self.assertIn(".hunt-news-must-read__status", css)
        self.assertIn(".hunt-news-brief-card {\n\tbackground: #fff;", css)
        self.assertIn(".huntlab-category-tabs{-webkit-backdrop-filter:blur(16px)", php)
        self.assertNotIn("body.home .huntlab-home-intro__copy {\n\t-webkit-backdrop-filter", css)

    def test_home_prioritizes_latest_posts_and_unifies_schema_identity(self):
        php = (PLUGIN / "huntlab-warm-editorial.php").read_text(encoding="utf-8")
        css = (PLUGIN / "assets/warm-editorial.css").read_text(encoding="utf-8")

        self.assertNotIn("shell.insertAdjacentElement('afterend',section)", php)
        self.assertIn("Hunt News · 검증된 문제 해결 라이브러리", php)
        self.assertIn("aioseo_schema_output", php)
        self.assertIn("Organization", php)
        self.assertIn("HuntLab 운영자", php)
        self.assertIn("hunt_news_editorial_author_link", php)
        self.assertIn("home_url( '/about/' )", php)
        self.assertIn("kadence_author_use_profile_link", php)
        self.assertIn("hunt_news_editorial_author_name", php)
        self.assertIn("https://github.com/sungpyo9053/blog", php)
        self.assertIn("aspect-ratio: 3.2 / 1", css)
        self.assertIn("white-space: nowrap", css)
        self.assertIn("body.home .content-wrap.kadence-posts-list", css)
        self.assertIn("repeat(2, minmax(0, 1fr))", css)
        self.assertIn("grid-template-columns: 112px minmax(0, 1fr)", css)
        self.assertIn("hunt-news-home-notices", php)
        self.assertIn("공식 원문, 독립 보도와 직접 검증을 구분합니다", php)
        self.assertIn("body:is(.home, .category) #main.site-main", css)
        self.assertIn("is_home() || is_front_page() || is_category()", php)
        self.assertIn("body:is(.home, .category) .content-wrap.kadence-posts-list", css)
        self.assertIn("우리 인기뉴스", php)
        self.assertIn("hunt-news-popular__tabs", php)
        self.assertIn("실시간 인기", php)
        self.assertIn('role="tablist"', php)
        self.assertIn('role="tabpanel"', php)
        self.assertIn('data-popular-tab="weekly"', php)
        self.assertIn("event.key==='ArrowRight'", php)
        self.assertIn("hunt_news_popular_rows( 10, 1 )", php)
        self.assertIn("hunt_news_popular_rows( 10, 7 )", php)
        self.assertIn("trend_arrow", php)
        self.assertIn("hunt-news-popular__toggle", php)
        self.assertIn("aria-expanded=\"false\"", php)
        self.assertIn("event.key==='Escape'", php)
        self.assertNotIn("if ( ! $is_category ) {\n\t\thunt_news_render_popular_news();", php)
        self.assertIn("wp_html_excerpt", php)
        self.assertIn("hunt-news/v1", php)
        self.assertIn("recordPopularRead", php)
        self.assertIn("GA4 조회와 30초 이상·25% 이상 읽은 신호 반영", php)
        self.assertIn(".hunt-news-popular__list", css)
        self.assertIn("Modern newsroom finish", css)
        self.assertIn("--huntlab-ink: #111820", css)
        self.assertIn("--huntlab-terracotta: #173b5f", css)
        self.assertIn("filter: grayscale(0.68)", css)
        self.assertIn("border-radius:2px!important", php)
        self.assertIn("Final modern newsroom overrides", css)
        self.assertIn("max-width: 760px", css)
        self.assertIn("grid-template-columns: 34px minmax(0, 1fr) 42px", css)
        self.assertIn(".hunt-news-popular__trend--up", css)
        self.assertIn(".hunt-news-popular__tab.is-active", css)
        self.assertIn(".hunt-news-popular__tabpanel[hidden]", css)
        self.assertIn("grid-template-columns: 1fr 1fr", css)
        self.assertIn("Narrow screens use a scroll-persistent popular-news drawer", css)
        self.assertIn("position: fixed", css)
        self.assertIn("translateX(calc(100% - 46px))", css)
        self.assertIn("hunt-news-content-shell", php)
        self.assertIn("grid-template-columns: minmax(0, 1fr) 340px", css)
        self.assertIn("position: sticky", css)
        self.assertIn("desktop.matches?'true':'false'", php)
        self.assertIn("grid-template-columns: 78px minmax(0, 1fr)", css)
        self.assertIn("position: absolute", css)
        self.assertIn("margin: 0 0 0 calc(50% - 50vw)", css)
        self.assertIn("right: 0", css)

    def test_home_is_a_verified_problem_solving_library(self):
        php = (PLUGIN / "huntlab-warm-editorial.php").read_text(encoding="utf-8")
        css = (PLUGIN / "assets/warm-editorial.css").read_text(encoding="utf-8")
        self.assertIn("WordPress 자동화 문제를<br>코드와 테스트로 검증합니다.", php)
        self.assertIn("function hunt_news_verified_posts", php)
        self.assertIn("array( 50, 132 )", php)
        self.assertIn("대표 해결 사례", php)
        self.assertIn("문제별 찾아보기", php)
        self.assertIn("해결 과정 보기", php)
        self.assertIn("VERIFIED CASE", php)
        self.assertIn("Daily Briefing", php)
        self.assertNotIn("독립 해설 주 2회 · 주간 회고 1회", php)
        self.assertIn("hunt_news_verified_case_header", php)
        self.assertIn("같은 문제군의 검증 글", php)
        self.assertIn("hunt_news_verified_case_comments", php)
        self.assertIn("kadence_post_layout", php)
        self.assertIn("theme_mod_post_related", php)
        self.assertIn("$layout['navigation'] = 'hide'", php)
        self.assertIn("HuntLab 운영자", php)
        self.assertIn(".hunt-news-case-grid", css)
        self.assertIn("@media(max-width:700px)", css)
        self.assertIn("body.hunt-news-verified-case .post-navigation", css)

    def test_home_briefing_dashboard_uses_observed_wordpress_data(self):
        php = (PLUGIN / "huntlab-warm-editorial.php").read_text(encoding="utf-8")
        css = (PLUGIN / "assets/warm-editorial.css").read_text(encoding="utf-8")

        self.assertIn("function hunt_news_briefing_posts", php)
        self.assertIn("'post_status'            => 'publish'", php)
        self.assertIn("function hunt_news_briefing_keywords", php)
        self.assertIn("get_the_tags", php)
        self.assertIn("function hunt_news_briefing_timeline", php)
        self.assertIn("function hunt_news_latest_briefing_manifest", php)
        self.assertIn("$publication_mode = (string) ( $manifest['publication_mode'] ?? 'legacy_top2' )", php)
        self.assertIn("$expected_publications = 'briefing_only' === $publication_mode ? 0 : 2", php)
        self.assertIn("return $expected_publications === count( $published ) ? $manifest : array()", php)
        self.assertIn("function hunt_news_briefing_display_date", php)
        self.assertIn("$manifest['analysis']['generated_at']", php)
        self.assertIn("hunt_news_briefing_display_date( $manifest )", php)
        self.assertNotIn("Hunt News <?php echo esc_html( is_singular( 'hunt_briefing' ) ? get_the_date( 'Y-m-d', get_queried_object_id() ) : wp_date( 'Y-m-d' ) ); ?>", php)
        self.assertIn("function hunt_news_manifest_signal_posts", php)
        self.assertIn("function hunt_news_store_briefing_manifest", php)
        self.assertIn("'/briefing-run'", php)
        self.assertIn("current_user_can( 'edit_posts' )", php)
        self.assertIn("invalid_briefing_publications", php)
        self.assertIn("invalid_briefing_analysis", php)
        self.assertIn("hunt_news_briefing_manifest", php)
        self.assertIn("발행 시점에 따라 다시 볼 뉴스를 나눴습니다", php)
        self.assertNotIn("if ( ! $selected ) {\n\t\t\tforeach ( $posts as $post )", php)
        self.assertIn("id=\"hunt-news-briefing-board\"", php)
        self.assertIn("if ( ! $is_category && ( $manifest || $brief_posts ) )", php)
        self.assertIn("$lead = $brief_posts ? $brief_posts[0] : null", php)
        self.assertIn("핵심 신호", php)
        self.assertIn("오늘의 키워드", php)
        self.assertIn("확인 타임라인", php)
        self.assertIn("어제의 판단 복기", php)
        self.assertIn("$analysis['retrospective']['items']", php)
        self.assertIn("$retrospective_counts", php)
        self.assertIn("hunt-news-retrospective__summary", php)
        self.assertIn("Hunt News 선정 오늘의 필독", php)
        self.assertIn("공식 원문, 독립 출처와 실무 영향을 대조해 고른", php)
        self.assertIn("$must_read_display_count", php)
        self.assertIn("고른 <?php echo esc_html( (string) $must_read_display_count ); ?>개", php)
        self.assertNotIn("고른 5개입니다", php)
        self.assertIn("지금 놓치면 아쉬운 기술 뉴스", php)
        self.assertIn('id="hunt-news-decision-matrix-title"', php)
        self.assertIn("적용 판단", php)
        self.assertIn("개발자 인사이트", php)
        self.assertIn("지켜볼 것", php)
        self.assertIn("$analysis['matrix']", php)
        self.assertIn("$analysis['developer_insights']", php)
        self.assertIn("$analysis['watchlist']", php)
        self.assertIn("오늘 수집한 기술 뉴스", php)
        self.assertIn("날짜 아카이브", php)
        self.assertIn("hunt_briefing", php)
        self.assertNotIn('data-brief-view=', php)
        self.assertNotIn('data-brief-card-index=', php)
        self.assertNotIn("hunt-news-brief-card--feed", php)
        self.assertNotIn("$briefing_feed_items", php)
        self.assertNotIn("hunt-news-brief-view-controls", php)
        self.assertIn("전체 수집원은 아래에서 분야별로 확인할 수 있습니다", php)
        self.assertIn("전체 보고서와 수집원 보기", php)
        self.assertIn("$is_briefing_detail = is_singular( 'hunt_briefing' );", php)
        self.assertIn("$is_briefing_detail && $source_groups", php)
        self.assertIn("hunt-news-briefing-overview--compact", php)
        self.assertNotIn('class="hunt-news-brief-card__decision"', php)
        self.assertIn("hunt_news_source_time_label", php)
        self.assertIn("'m.d H:i'", php)
        self.assertIn("array_slice( $must_read_items, 0, $must_read_display_count )", php)
        self.assertIn("--hunt-brief-navy", css)
        self.assertIn(".hunt-news-briefing-overview", css)
        self.assertIn(".hunt-news-reader-summary", css)
        self.assertIn('id="hunt-news-reader-summary"', php)
        self.assertIn("핵심 변화", php)
        self.assertIn("연결된 근거", php)
        self.assertIn("행동 시점", php)
        self.assertIn("선별 원문", php)
        self.assertNotIn("Legacy 실제 발행 후보", php)
        self.assertNotIn("Reviewer·Publisher 통과", php)
        self.assertNotIn("비발행 병렬 비교", php)
        self.assertNotIn("수집 <?php echo esc_html", php)
        self.assertIn("DAILY BRIEF", php)
        self.assertIn("grid-template-columns: 14px minmax(0, 0.82fr) minmax(0, 1.18fr)", css)
        self.assertIn(".hunt-news-signal-card > div", css)
        self.assertIn("overflow-wrap: anywhere", css)
        self.assertIn("white-space: normal", css)
        self.assertIn(".hunt-news-action-timeline", css)
        self.assertIn(".hunt-news-retrospective__summary", css)
        self.assertIn(".hunt-news-focus", css)
        self.assertIn(".hunt-news-decision-matrix", css)
        self.assertIn(".hunt-news-synthesis", css)
        self.assertIn(".hunt-news-focus__heading h3 {\n\tcolor: #fff;", css)
        self.assertIn(".hunt-news-must-read__status", css)
        self.assertIn("@media (max-width: 767px)", css)

    def test_daily_briefing_is_primary_and_has_month_date_navigation(self):
        php = (PLUGIN / "huntlab-warm-editorial.php").read_text(encoding="utf-8")
        css = (PLUGIN / "assets/warm-editorial.css").read_text(encoding="utf-8")

        self.assertIn("Version: 7.0.0", php)
        self.assertIn("function hunt_news_briefing_archive_months", php)
        self.assertIn("function hunt_news_render_briefing_navigation", php)
        self.assertIn("class=\"hunt-news-report-shell\"", php)
        self.assertIn("id=\"hunt-news-date-nav\"", php)
        self.assertIn("Hunt News [", php)
        self.assertIn("Hunt News <?php echo esc_html( get_the_date( 'Y-m-d', $post ) ); ?>", php)
        self.assertIn("is_post_type_archive( 'hunt_briefing' )", php)
        self.assertIn("'post_title' => 'Hunt News ' . $briefing_date", php)
        self.assertIn("$briefing_timestamp = strtotime( $safe['generated_at'] )", php)
        self.assertIn("'post_date' => wp_date( 'Y-m-d H:i:s', $briefing_timestamp )", php)
        self.assertIn("'post_date_gmt' => gmdate( 'Y-m-d H:i:s', $briefing_timestamp )", php)
        self.assertIn("$key = get_the_date( 'Y.m', $post )", php)
        self.assertIn("$current_datetime = current_datetime()", php)
        self.assertIn("$current_datetime->modify( '+1 day' )->format( 'Y.m' )", php)
        self.assertIn("$tomorrow_month !== $current_month", php)
        self.assertIn("$months = array( $tomorrow_month => array() ) + $months", php)
        self.assertIn("내일 04시 첫 브리핑이 발행됩니다.", php)
        self.assertIn("DAILY BRIEF", php)
        self.assertIn("body.hunt-news-briefing-mode #main.site-main", css)
        self.assertIn("grid-template-columns: 238px minmax(0, 1fr)", css)
        self.assertIn("position: sticky", css)
        self.assertIn(".hunt-news-date-nav.is-open", css)
        self.assertIn("aria-expanded", php)
        self.assertIn("hunt-news-brief-card--source", php)
        self.assertIn("hunt-news-brief-card__rank", php)
        self.assertIn("$must_read_categories", php)
        self.assertIn("'AI/ML 핵심', '개발 트렌드', 'AI 공식 블로그', '국내 IT', '국내 시사'", php)
        self.assertIn("'weekly-tech-review'", php)
        self.assertIn("'주간 기술 회고'", php)
        self.assertIn("count( $must_read_items ) < 10", php)
        self.assertIn("$selected_urls", php)
        self.assertIn("daily-briefing-analysis.v1", php)
        self.assertIn("daily-briefing-analysis.v2", php)
        self.assertIn("7 < $action_count", php)
        self.assertIn("function hunt_news_briefing_search_metadata", php)
        self.assertIn("function hunt_news_home_search_metadata", php)
        self.assertIn("WordPress 자동발행 문제 해결 라이브러리 - Hunt News", php)
        self.assertIn("hunt_news_render_evidence_library_home", php)
        self.assertIn("대표 해결 사례", php)
        self.assertIn("DAILY BRIEF", php)
        self.assertIn("hunt_news_briefing_robots", php)
        self.assertIn("hunt_news_briefing_aioseo_robots", php)
        self.assertIn("add_filter( 'aioseo_robots_meta', 'hunt_news_briefing_aioseo_robots'", php)
        self.assertIn("$robots['noindex'] = 'noindex'", php)
        self.assertIn("hunt_news_briefing_aioseo_sitemap_indexes", php)
        self.assertIn("'/hunt_briefing-sitemap'", php)
        self.assertIn("'/post-archive-sitemap.xml'", php)
        self.assertIn("add_filter( 'aioseo_sitemap_posts', 'hunt_news_briefing_aioseo_sitemap_posts', 20, 2 )", php)
        self.assertIn("add_filter( 'aioseo_sitemap_post_archives', 'hunt_news_briefing_aioseo_sitemap_archives'", php)
        self.assertIn("add_filter( 'aioseo_title', 'hunt_news_briefing_search_title'", php)
        self.assertIn("add_filter( 'aioseo_description', 'hunt_news_briefing_search_description'", php)
        self.assertIn("get_post_meta( $post_id, '_hunt_news_briefing_manifest', true )", php)
        self.assertIn("' 기술 브리핑 - Hunt News'", php)
        self.assertIn("hunt_news_sanitize_daily_analysis", php)
        self.assertIn("Hunt News 한 줄 판단", php)
        self.assertIn('id="hunt-news-synthesis-title"', php)
        self.assertIn("why_it_matters", php)
        self.assertIn("source_title_translations", php)
        self.assertIn("hunt-news-source-card__translated", php)
        self.assertIn(".hunt-news-source-card__translated", css)
        self.assertIn(".hunt-news-source-board { order: 9; }", css)
        self.assertIn("grid-template-columns: repeat(5, minmax(0, 1fr))", css)
        self.assertIn(".hunt-news-brief-card--source h4", css)
        self.assertNotIn('<h4><a href="<?php echo esc_url( (string) ( $item[\'url\'] ?? \'\' ) ); ?>"', php)

    def test_empty_category_archives_do_not_become_low_value_landing_pages(self):
        php = (PLUGIN / "huntlab-warm-editorial.php").read_text(encoding="utf-8")

        self.assertIn("function hunt_news_noindex_empty_category_archives", php)
        self.assertIn("add_filter( 'wp_robots', 'hunt_news_noindex_empty_category_archives'", php)
        self.assertIn("function hunt_news_redirect_empty_special_editorial_archive", php)
        self.assertIn("array( 'weekly-tech-review', 'technical-explainer' )", php)
        self.assertIn("'technical-explainer'", php)
        self.assertIn("get_post_type_archive_link( 'hunt_briefing' )", php)
        self.assertIn("wp_safe_redirect", php)
        self.assertIn("302", php)

    def test_real_read_signal_requires_visible_time_and_scroll_depth(self):
        php = (PLUGIN / "huntlab-warm-editorial.php").read_text(encoding="utf-8")

        self.assertIn("huntlab_engaged_read", php)
        self.assertIn("document.visibilityState!=='visible'", php)
        self.assertIn("activeMs>=30000", php)
        self.assertIn("maxDepth>=25", php)
        self.assertIn("window.gtag||window.__gtagTracker", php)
        self.assertIn("huntlab_internal_click", php)
        self.assertIn("destination.origin!==window.location.origin", php)
        self.assertIn("link_area", php)
        self.assertIn("huntlab_article_complete", php)
        self.assertIn("huntlab_article_share", php)
        self.assertIn("huntlab_return_visit", php)
        self.assertNotIn("huntlab_briefing_filter", php)
        self.assertIn("huntlab_briefing_source_click", php)
        self.assertIn("briefing_archive", php)
        self.assertIn("data-huntlab-share", php)
        self.assertIn("분야 더 보기", php)
        self.assertIn("get_category_link", php)
        self.assertIn("activeMs>=45000", php)

    def test_category_archives_have_specific_copy_and_optimized_hero_images(self):
        php = (PLUGIN / "huntlab-warm-editorial.php").read_text(encoding="utf-8")
        css = (PLUGIN / "assets/warm-editorial.css").read_text(encoding="utf-8")
        image_dir = PLUGIN / "assets/categories"

        expected = {
            "ml-algorithms": "점수보다",
            "harness-engineering": "자동화보다",
            "system-architecture": "구성요소보다",
            "tech": "도구보다",
            "ai": "모델보다",
            "build-log": "결과보다",
            "economy": "숫자보다",
            "society": "이슈보다",
            "hot-issue": "속보보다",
        }
        for slug, copy in expected.items():
            self.assertIn(f"'{slug}'", php)
            self.assertIn(copy, php)
            image = image_dir / f"{slug}.webp"
            self.assertTrue(image.is_file(), image)
            self.assertLess(image.stat().st_size, 150_000, image)

        self.assertIn("huntlab-home-intro--category", php)
        self.assertIn("loading=\"eager\"", php)
        self.assertIn("fetchpriority=\"high\"", php)
        self.assertIn(".huntlab-home-intro__visual", css)
        self.assertIn("body.category .post-archive-hero-section", css)

    def test_huntlab_site_icon_is_square_and_search_engine_ready(self):
        png = PLUGIN / "assets/huntlab-site-icon.png"
        svg = PLUGIN / "assets/huntlab-site-icon.svg"

        self.assertTrue(png.is_file())
        self.assertTrue(svg.is_file())
        with Image.open(png) as image:
            self.assertEqual((512, 512), image.size)
            self.assertEqual("PNG", image.format)

        svg_text = svg.read_text(encoding="utf-8")
        self.assertIn('viewBox="0 0 96 96"', svg_text)
        self.assertIn("Hunt News의 강아지 로고", svg_text)

    def test_category_tabs_include_briefing_navigation(self):
        php = CATEGORY_TABS.read_text(encoding="utf-8")
        self.assertIn("Version: 4.0.0", php)
        self.assertIn("오늘 브리핑", php)
        self.assertIn("날짜 아카이브", php)
        self.assertIn("주간 회고", php)
        self.assertIn("weekly-tech-review", php)
        self.assertIn("기술 해설", php)
        self.assertIn("technical-explainer", php)
        self.assertIn("is_category( 'technical-explainer' )", php)
        self.assertIn("has_category( 'technical-explainer' )", php)
        self.assertIn("has_category( 'weekly-tech-review' )", php)
        self.assertIn("is_category( 'weekly-tech-review' )", php)
        self.assertIn("0 < (int) $weekly_category->count", php)
        self.assertNotIn('id="hunt-news-reading-guide"', (PLUGIN / "huntlab-warm-editorial.php").read_text(encoding="utf-8"))
        self.assertIn("이용 가이드", php)
        self.assertIn("home_url( '/about/' )", php)
        self.assertIn("get_post_type_archive_link( 'hunt_briefing' )", php)
        self.assertIn('data-hunt-news-nav=', php)
        self.assertIn('aria-label="Hunt News 콘텐츠 탐색"', php)
        self.assertIn("hunt_news_redirect_legacy_categories", php)
        self.assertIn("wp_safe_redirect( $target, 301 )", php)
        self.assertIn("position:sticky;top:0;overflow-x:auto", php)
        self.assertIn("justify-content:center", php)
        self.assertIn("intro.insertAdjacentElement('afterend',nav)", php)
        self.assertIn("margin-left:calc(50% - 50vw)", php)
        self.assertIn("min-height:44px", php)

    def test_home_exposes_latest_explainer_only_after_publication(self):
        php = (PLUGIN / "huntlab-warm-editorial.php").read_text(encoding="utf-8")
        css = (PLUGIN / "assets/warm-editorial.css").read_text(encoding="utf-8")

        self.assertIn("function hunt_news_latest_special_post", php)
        self.assertIn("hunt_news_latest_special_post( 'technical-explainer' )", php)
        self.assertIn('id="hunt-news-deep-read-title"', php)
        self.assertIn("이번 주 깊이 읽기", php)
        self.assertIn("기술 해설 모아보기", php)
        self.assertIn(".hunt-news-deep-read", css)

    def test_editorial_home_removes_legacy_loop_from_server_response(self):
        php = (PLUGIN / "huntlab-warm-editorial.php").read_text(encoding="utf-8")
        css = (PLUGIN / "assets/warm-editorial.css").read_text(encoding="utf-8")

        self.assertIn("Version: 7.0.0", php)
        self.assertIn("function hunt_news_remove_legacy_home_loop", php)
        self.assertIn("$query->is_main_query()", php)
        self.assertIn("add_filter( 'the_posts', 'hunt_news_remove_legacy_home_loop', 99, 2 )", php)
        self.assertIn("$query->found_posts    = 0", php)
        self.assertNotIn("<li><b>1</b><strong>무엇이 바뀌었나</strong>", php)
        self.assertIn("counter-reset:hunt-news-method", css)
        self.assertIn("counter(hunt-news-method,decimal-leading-zero)", css)

    def test_editorial_home_uses_reader_feed_without_fake_engagement(self):
        php = (PLUGIN / "huntlab-warm-editorial.php").read_text(encoding="utf-8")
        css = (PLUGIN / "assets/warm-editorial.css").read_text(encoding="utf-8")

        self.assertIn("function hunt_news_reading_minutes", php)
        self.assertIn("$characters", php)
        self.assertIn("$code_lines", php)
        self.assertIn("data-hunt-news-group", php)
        self.assertIn("data-hunt-news-case-group", php)
        self.assertIn("hunt_news_verified_case_category_label", php)
        self.assertIn("hunt_news_verified_case_category_term_links", php)
        self.assertIn("add_filter( 'term_links-category'", php)
        self.assertIn("body.home .huntlab-category-tabs{display:none}", css)
        self.assertIn("preg_match_all( '/[\\p{L}\\p{N}]/u'", php)
        self.assertIn("$explainer_feed   = $explainers ? array_slice( $explainers, 1 )", php)
        self.assertIn('class="hunt-news-feed-tabs"', php)
        self.assertIn('class="hunt-news-devto-layout"', php)
        self.assertIn('class="hunt-news-devto-feed"', php)
        self.assertIn('class="hunt-news-devto-sidebar"', php)
        self.assertNotIn('<main id="hunt-news-editor-picks"', php)
        self.assertIn("has_post_thumbnail", php)
        self.assertIn("get_the_post_thumbnail", php)
        self.assertIn("hunt-news-feed-card--no-image", php)
        self.assertIn(".hunt-news-feed-card--no-image .hunt-news-feed-card__body{grid-column:1/-1}", css)
        self.assertIn("분 읽기", php)
        self.assertIn("에디터 선정", php)
        self.assertIn("최신 해설", php)
        self.assertIn("날짜별 브리핑", php)
        self.assertNotIn("좋아요", php)
        self.assertNotIn("댓글 수", php)
        self.assertIn("grid-template-columns:minmax(0,1fr) 310px", css)
        self.assertIn("DEV Community navigation with Velog-like visual cards", css)

    def test_category_tabs_remove_empty_category_counts(self):
        php = CATEGORY_TABS.read_text(encoding="utf-8")
        self.assertNotIn("function huntlab_category_tabs_recent_slugs()", php)
        self.assertNotIn("wp_count_posts( 'post' )", php)
        self.assertNotIn("'count' => (int) $category->count", php)
        self.assertNotIn("최근 3일 내 새 글 있음", php)
        self.assertNotIn("window.location.hash==='#hunt-news-source-title'", php)


if __name__ == "__main__":
    unittest.main()
