"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (0.005 * 1)
assert math.isclose(value, 0.005, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '현실 속도(RTF 1)에서 5 ms 지연의 시뮬레이션 시간 오차(초)', "actual": value})
value = (0.005 * 10)
assert math.isclose(value, 0.05, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '10배속(RTF 10)에서 같은 지연의 시뮬레이션 시간 오차(초)', "actual": value})
value = (0.005 * 0.5)
assert math.isclose(value, 0.0025, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '느린 시뮬레이션(RTF 0.5)에서 같은 지연의 시뮬레이션 시간 오차(초)', "actual": value})
value = (2 * 0.005 * 1)
assert math.isclose(value, 0.01, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '2 m/s 로봇, RTF 1에서 위치 오차(m)', "actual": value})
value = (2 * 0.005 * 10)
assert math.isclose(value, 0.1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '2 m/s 로봇, RTF 10에서 위치 오차(m)', "actual": value})
value = (0.02 / 0.005)
assert math.isclose(value, 4, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '허용 오차 0.02초, 지연 0.005초일 때 최대 RTF', "actual": value})
value = (10 / 100)
assert math.isclose(value, 0.1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'RTF 10, /clock 100 Hz일 때 한 틱의 시뮬레이션 시간 간격(초)', "actual": value})
value = (10 / 1000)
assert math.isclose(value, 0.01, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'RTF 10, /clock 1000 Hz일 때 한 틱의 시뮬레이션 시간 간격(초)', "actual": value})
value = (0.005 * 10 + 10 / 1000)
assert math.isclose(value, 0.06, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '반례: RTF 10에서 /clock을 1000 Hz로 올려도 남는 지연 항과 틱 항의 합(초)', "actual": value})
print(json.dumps(results, ensure_ascii=False))
