"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (5000 - 4500)
assert math.isclose(value, 500, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Automatic: 노드 전체 기준 마지막 발행(진단 4500 ms)부터 판정 시각까지의 경과 시간(ms)', "actual": value})
value = (1000 - (5000 - 4500))
assert math.isclose(value, 500, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Automatic: lease 1000 ms에서 남은 여유(ms). 양수이므로 카메라가 멈췄어도 살아 있는 것으로 판정됩니다', "actual": value})
value = (5000 - 2000)
assert math.isclose(value, 3000, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Manual by topic: 카메라가 마지막으로 생존을 알린 2000 ms부터 경과한 시간(ms)', "actual": value})
value = (1000 - (5000 - 2000))
assert math.isclose(value, -2000, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Manual by topic: lease 1000 ms에서 남은 여유(ms). 음수이므로 liveliness를 잃는 조건입니다', "actual": value})
value = (2000 + 1000)
assert math.isclose(value, 3000, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Manual by topic에서 liveliness를 잃는 것으로 판정될 수 있는 가장 이른 시각(ms): 마지막 알림 + lease', "actual": value})
value = ((5000 - 2000) / 500)
assert math.isclose(value, 6, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '카메라가 멈춘 2000~5000 ms 동안 Automatic 판정을 계속 갱신해 준 진단 발행 횟수', "actual": value})
value = (1000 / 50)
assert math.isclose(value, 20, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'lease 1000 ms 안에 들어가는 카메라 발행 주기(50 ms)의 개수', "actual": value})
value = (40 - 50)
assert math.isclose(value, -10, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '경계 반례: lease 40 ms를 50 ms 주기 publisher에 걸면 정상 발행 사이에도 여유가 음수입니다(ms)', "actual": value})
value = (500 - 1000)
assert math.isclose(value, -500, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '호환성 반례: publisher는 lease 1000 ms를 제공하고 subscription은 500 ms를 요청할 때 (요청 − 제공)(ms). 음수이므로 문서 표상 비호환입니다', "actual": value})
print(json.dumps(results, ensure_ascii=False))
