"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (4 * 1.25)
assert math.isclose(value, 5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '4개 동시 빌드 시 최대 메모리 합계(GB)', "actual": value})
value = (4 * 1.25 - 4)
assert math.isclose(value, 1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '4 GB RAM 대비 초과량(GB)', "actual": value})
value = (1 * 1.25)
assert math.isclose(value, 1.25, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'sequential 빌드의 최대 메모리(GB)', "actual": value})
value = (4 / 1.25)
assert math.isclose(value, 3.2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'RAM에 들어가는 동시 빌드 수(소수점 이하를 버린 정수 부분이 상한)', "actual": value})
value = (30 + 40 + 50 + 60)
assert math.isclose(value, 180, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'sequential 총 빌드 시간: 패키지 시간의 합(초)', "actual": value})
value = ((30 + 40 + 50 + 60) / 4)
assert math.isclose(value, 45, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '독립 패키지 4개를 동시에 빌드할 때 작업량 기준 하한(초)', "actual": value})
value = (60)
assert math.isclose(value, 60, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '독립 패키지 병렬 빌드의 실제 하한은 가장 긴 패키지(초)', "actual": value})
value = ((30 + 40 + 50 + 60) / 60)
assert math.isclose(value, 3, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'sequential이 이상적 병렬보다 몇 배 걸리는지', "actual": value})
value = (30 + 40 + 50 + 60)
assert math.isclose(value, 180, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '반례: A→B→C→D 의존성 체인이면 병렬로도 순차 합과 같다(초)', "actual": value})
value = ((4 * 1.25) / 16)
assert math.isclose(value, 0.3125, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '16 GB 데스크톱에서 4개 동시 빌드가 차지하는 RAM 비율', "actual": value})
print(json.dumps(results, ensure_ascii=False))
