"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (1000 / 20)
assert math.isclose(value, 50, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '카메라 발행 주기(ms): 1000 / 20 Hz', "actual": value})
value = (1000 / 5)
assert math.isclose(value, 200, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '상태 토픽 발행 주기(ms): 1000 / 5 Hz', "actual": value})
value = (500 - 1000 / 5)
assert math.isclose(value, 300, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Automatic, 카메라만 멈춤: lease 500 − 같은 노드 상태 토픽의 갱신 간격 200 → 양수라 이벤트 없음', "actual": value})
value = (500 - 1000)
assert math.isclose(value, -500, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Automatic, 노드 전체가 1초 멈춤: lease 500 − 1000 → 음수라 Liveliness lost 조건', "actual": value})
value = (500 - 1000 / 20)
assert math.isclose(value, 450, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Manual by topic, 카메라 정상: lease 500 − 카메라 자신의 알림 간격 50', "actual": value})
value = (500 - 1000)
assert math.isclose(value, -500, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Manual by topic, 카메라만 1초 멈춤: 상태 토픽과 무관하게 lease 500 − 1000 → 음수', "actual": value})
value = (500 - 1000 / 2)
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '경계 사례: Automatic에서 상태 토픽이 2 Hz로 느려진 채 카메라가 멈춤 → 여유 0, 원문은 같은 값의 판정을 정하지 않음', "actual": value})
value = (300 - 500)
assert math.isclose(value, -200, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'lease duration 호환성: 구독자 요청 300 − 발행자 제공 500 → 음수이면 표의 y < x 행에 해당해 비호환', "actual": value})
print(json.dumps(results, ensure_ascii=False))
