"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (0.5 / 8)
assert math.isclose(value, 0.0625, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'c=0.5 rad/s, Kp=8에서 정상상태 오차 c/Kp (rad)', "actual": value})
value = (8 * 0.0625)
assert math.isclose(value, 0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '그 정상상태에서 필요한 명령 속도 Kp×e_ss (rad/s): vmax 2보다 작아 포화 없음', "actual": value})
value = (1.5 / 8)
assert math.isclose(value, 0.1875, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'c=1.5 rad/s, Kp=8에서 정상상태 오차 (rad): 명령 1.5도 vmax 2 이하라 성립', "actual": value})
value = (2 / 8)
assert math.isclose(value, 0.25, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '포화가 풀리는 경계 오차 vmax/Kp (rad)', "actual": value})
value = ((1 - 0.25) / (2 - 0))
assert math.isclose(value, 0.375, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '비교 기준: 정지 목표(c=0)에서 e0=1 rad부터 경계 0.25 rad까지 걸리는 시간 (s)', "actual": value})
value = ((1 - 0.25) / (2 - 0.5))
assert math.isclose(value, 0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'c=0.5에서 같은 구간을 따라잡는 시간 (s): 줄어드는 속도는 vmax − c = 1.5 rad/s', "actual": value})
value = ((1 - 0.25) / (2 - 1.5))
assert math.isclose(value, 1.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'c=1.5에서 같은 구간을 따라잡는 시간 (s): 줄어드는 속도는 0.5 rad/s로 정지 목표의 4배 시간', "actual": value})
value = (2 - 2)
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '경계 c=vmax=2: 포화 구간에서 오차가 줄어드는 속도 (rad/s)는 0이라 e0=1에서 줄지 않음', "actual": value})
value = ((2.5 - 2) * 4)
assert math.isclose(value, 2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '반례 c=2.5 > vmax: 포화된 채 4초 동안 늘어나는 오차 (rad), Kp는 식에 나오지 않음', "actual": value})
value = (2.5 / 32)
assert math.isclose(value, 0.078125, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '반례: Kp=32로 올렸을 때 선형 공식 c/Kp가 주는 정상상태 오차 예측 (rad)', "actual": value})
value = (32 * 0.078125)
assert math.isclose(value, 2.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '그 예측 오차를 유지하는 데 필요한 명령 속도 Kp×(c/Kp) (rad/s): vmax 2를 넘어 실현할 수 없음', "actual": value})
print(json.dumps(results, ensure_ascii=False))
