"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (90 - 0)
assert math.isclose(value, 90, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '북쪽(방위 0도)을 바라볼 때의 ROS yaw(도)', "actual": value})
value = (90 - 90)
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '동쪽(방위 90도)을 바라볼 때의 ROS yaw(도)', "actual": value})
value = (90 - 30)
assert math.isclose(value, 60, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '방위 30도(북북동)를 올바르게 변환한 yaw(도)', "actual": value})
value = ((90 - 30) - 30)
assert math.isclose(value, 30, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '방위 30도를 변환 없이 yaw로 넣었을 때 생기는 방향 차이(도)', "actual": value})
value = ((90 - 45) - 45)
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '방위 45도에서는 변환 없는 구현도 차이가 0이 되는 경계 반례(도)', "actual": value})
value = ((90 - 30) - (30 - 90))
assert math.isclose(value, 120, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '방위 30도에 부호를 반대로 뺀 구현(bearing - 90)과의 방향 차이(도)', "actual": value})
value = (90 - 300 + 360)
assert math.isclose(value, 150, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '방위 300도(북서쪽)의 yaw를 360을 더해 정규화한 값(도)', "actual": value})
value = ((90 - 0) / 180 * 3.14159)
assert math.isclose(value, 1.570795, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '북쪽 yaw 90도를 라디안으로 바꾼 값(원주율 근사 3.14159)', "actual": value})
print(json.dumps(results, ensure_ascii=False))
