"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (2 * (1 - 0))
assert math.isclose(value, 2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '올바른 규약의 첫 명령 속도 Kp·(θd−θ) [rad/s]', "actual": value})
value = (2 * (0 - 1))
assert math.isclose(value, -2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '버그 A(오차를 θ−θd로 계산)의 첫 명령 속도 [rad/s]', "actual": value})
value = (1 - (0 + 2 * (1 - 0) * 0.1))
assert math.isclose(value, 0.8, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '올바른 규약에서 한 주기 뒤 오차 [rad]', "actual": value})
value = (1 - (0 + 2 * (0 - 1) * 0.1))
assert math.isclose(value, 1.2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '버그 A에서 한 주기 뒤 오차 [rad]', "actual": value})
value = (2 * ((0 + 2 * (0 - 1) * 0.1) - 1))
assert math.isclose(value, -2.4, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '버그 A에서 두 번째 주기의 명령 속도: 관절이 -0.2 rad로 밀려난 뒤 [rad/s]', "actual": value})
value = (1.2 * (1 + 2 * 0.1))
assert math.isclose(value, 1.44, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '버그 A에서 두 주기 뒤 오차: 1.2 rad에 다시 1+Kp·dt를 곱함 [rad]', "actual": value})
value = (1 - (0 - 2 * (1 - 0) * 0.1))
assert math.isclose(value, 1.2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '버그 B(모터 방향 반대, 실제속도 = −명령)에서 한 주기 뒤 오차 [rad]', "actual": value})
value = (1 - (0 + 4 * (0 - 1) * 0.1))
assert math.isclose(value, 1.4, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '반례: 버그 A 상태에서 게인을 4로 올렸을 때 한 주기 뒤 오차 [rad]', "actual": value})
value = (0.05 * (1 + 2 * 0.1))
assert math.isclose(value, 0.06, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '경계: 작은 점검 스텝 0.05 rad에서 버그 A의 한 주기 뒤 오차 [rad]', "actual": value})
value = (1 - (0 - 2 * (0 - 1) * 0.1))
assert math.isclose(value, 0.8, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '반례: 버그 A와 B가 함께 있을 때 한 주기 뒤 오차 [rad]', "actual": value})
print(json.dumps(results, ensure_ascii=False))
