"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (1000 / 20)
assert math.isclose(value, 50, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '20 Hz 센서의 발행 간격(ms)', "actual": value})
value = (50 - 100)
assert math.isclose(value, -50, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '반례: 구독자 요청 50ms − 발행자 제공 100ms (음수면 비호환, 연결 없음)', "actual": value})
value = (100 - 50)
assert math.isclose(value, 50, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '구독자 요청 100ms − 발행자 제공 50ms (양수면 호환)', "actual": value})
value = (80 - 80)
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '경계: 요청과 제공이 같은 80ms (0이면 호환)', "actual": value})
value = (40 - 1000 / 20)
assert math.isclose(value, -10, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '20 Hz 발행자가 제공 deadline 40ms를 걸 때: 제공 − 실제 간격 (음수면 발행자가 매 주기 약속 위반)', "actual": value})
value = (150 - 1000 / 10)
assert math.isclose(value, 50, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '10 Hz 발행자, 제공 deadline 150ms: 제공 − 실제 간격', "actual": value})
value = (200 - 150)
assert math.isclose(value, 50, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '같은 연결에서 구독자 요청 200ms − 제공 150ms (연결 시점 호환)', "actual": value})
value = (150 - 1000 / 5)
assert math.isclose(value, -50, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '연결 후 센서가 5 Hz로 느려짐: 제공 150ms − 실제 간격 (호환이어도 위반)', "actual": value})
print(json.dumps(results, ensure_ascii=False))
