"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (0 + 1)
assert math.isclose(value, 1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '의도한 발행: A 기준 B 원점 높이(m)', "actual": value})
value = (0.5 + 1)
assert math.isclose(value, 1.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'B에서 z=0.5 m인 점을 A로 표현(데이터 B→A, 높이 더함)', "actual": value})
value = (1.5 - 1)
assert math.isclose(value, 0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '왕복 검산: A에서 z=1.5 m인 점을 B로 되돌림(높이 줄어듦)', "actual": value})
value = (0 - 1)
assert math.isclose(value, -1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '방향을 뒤집어 발행했을 때 A 기준 B 원점 높이(m)', "actual": value})
value = (1 - (0 - 1))
assert math.isclose(value, 2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '뒤집힌 발행에서 원점이 의도한 위치와 벌어진 거리(m)', "actual": value})
value = ((0.5 + 1) - (0.5 - 1))
assert math.isclose(value, 2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '뒤집힌 발행에서 B의 z=0.5 m 점이 A에서 벌어진 거리(m): 원점과 같은 2배', "actual": value})
value = ((0.2 - (0 - 0.2)) / 0.2)
assert math.isclose(value, 2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'base_link→laser x=0.2 m를 반대로 발행했을 때 벌어진 거리 ÷ 발행 오프셋', "actual": value})
value = (0.3 / 0.3)
assert math.isclose(value, 1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '반례: 0.3 m 오프셋인데 보이는 어긋남도 0.3 m라면 비율은 1(방향 실수로 설명 안 됨)', "actual": value})
value = (0 - (0 * 0.2 + 1 * 0))
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '90° 회전 + 이동 t=(0.2, 0)의 역변환 이동량 x성분 −(Rᵀt)x', "actual": value})
value = (0 - ((0 - 1) * 0.2 + 0 * 0))
assert math.isclose(value, 0.2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '같은 역변환 이동량 y성분 −(Rᵀt)y: 단순 부호 반전값 0과 다름', "actual": value})
print(json.dumps(results, ensure_ascii=False))
