"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (1 / 20)
assert math.isclose(value, 0.05, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '20 Hz 카메라의 발행 간격(s)', "actual": value})
value = (0.1 - 1 / 20)
assert math.isclose(value, 0.05, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '정상 작동 중 카메라 deadline 0.1 s의 여유(s, 양수면 약속 이행 가능)', "actual": value})
value = ((10.25 - 10.0) - 0.1)
assert math.isclose(value, 0.15, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '카메라 정지 후 10.25 s 시점: 마지막 카메라 메시지 경과 - deadline(s, 양수면 deadline missed 조건)', "actual": value})
value = (1.0 - 1 / 100)
assert math.isclose(value, 0.99, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '같은 시점 automatic liveliness: lease 1.0 s - 마지막 IMU 메시지 경과 0.01 s(s, 양수라 카메라도 살아 있음으로 보임)', "actual": value})
value = (10.0 + 0.1)
assert math.isclose(value, 10.1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '카메라 토픽만 멈췄을 때 deadline missed 조건이 되는 시각(s)', "actual": value})
value = (10.0 + 1.0)
assert math.isclose(value, 11, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '노드 전체가 10.0 s에 멈췄을 때 liveliness lost 조건이 되는 시각(s)', "actual": value})
value = (1.0 / 0.1)
assert math.isclose(value, 10, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '노드 전체 정지에서 liveliness 탐지와 deadline 탐지에 걸리는 시간의 비', "actual": value})
value = (10.0 + 0.5)
assert math.isclose(value, 10.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '캡처 성공 시에만 assert하는 manual by topic, lease 0.5 s일 때 카메라 정지 탐지 시각(s)', "actual": value})
value = (0.5 - 1.0)
assert math.isclose(value, -0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '반례: subscriber 요청 lease 0.5 s - publisher 제공 lease 1.0 s(음수면 비호환, 연결 없음)', "actual": value})
print(json.dumps(results, ensure_ascii=False))
