"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = ((0.25 + 0.5 + 0.75 + 1.0) / 4)
assert math.isclose(value, 0.625, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '정상 버퍼에 저장된 관절각 평균 (rad)', "actual": value})
value = ((1.0 + 1.0 + 1.0 + 1.0) / 4)
assert math.isclose(value, 1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '참조만 쌓는 버퍼라는 가정에서 네 칸이 모두 마지막 값 1.0을 보일 때의 평균 (rad)', "actual": value})
value = (1.0 - 0.625)
assert math.isclose(value, 0.375, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '그 가정에서 생기는 평균 오차 (rad)', "actual": value})
value = (1.0 - 0.25)
assert math.isclose(value, 0.75, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '가장 오래된 원소의 오차: 첫 스텝의 실제 값 0.25 rad가 1.0으로 보일 때 (rad)', "actual": value})
value = ((0.5 - 0.25) / 0.125)
assert math.isclose(value, 2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '정상 버퍼에서 연속 관측으로 구한 차분 속도 (rad/s)', "actual": value})
value = ((1.0 - 1.0) / 0.125)
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '참조만 쌓는 버퍼에서 연속 관측으로 구한 차분 속도 (rad/s)', "actual": value})
value = (1.0 - 1.0)
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '경계 사례: 마지막 한 칸만 비교하는 테스트에서 나오는 차이 (rad)', "actual": value})
value = ((0.25 + 0.5 + 0.75 + 1.0) / 4 - 0.625)
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '대조군: 반환 전에 새 배열로 복사하면 평균이 정상 값과 같다 (rad)', "actual": value})
print(json.dumps(results, ensure_ascii=False))
