"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (1 / 2)
assert math.isclose(value, 0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=2 1/s의 시간상수(s)', "actual": value})
value = (1 / 4)
assert math.isclose(value, 0.25, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=4 1/s의 시간상수(s): 이득 두 배면 절반', "actual": value})
value = (0.5 / (2 * 0.5))
assert math.isclose(value, 0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '접선 해석: 오차 0.5 rad를 초기 감소율 Kp×e0로 줄이면 걸리는 시간(s)이 1/Kp와 같음', "actual": value})
value = (2 * 0.5)
assert math.isclose(value, 1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=2, 초기 오차 0.5 rad의 초기 속도 명령(rad/s)', "actual": value})
value = (4 * 0.5)
assert math.isclose(value, 2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=4, 초기 오차 0.5 rad의 초기 속도 명령(rad/s)', "actual": value})
value = (2 * 0.5 - 1.5)
assert math.isclose(value, -0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=2 초기 명령에서 한계 1.5 rad/s를 뺀 값: 음수면 여유', "actual": value})
value = (4 * 0.5 - 1.5)
assert math.isclose(value, 0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=4 초기 명령에서 한계 1.5 rad/s를 뺀 값: 양수면 초과', "actual": value})
value = (1.5 / 2)
assert math.isclose(value, 0.75, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=2의 포화 경계 오차 vmax/Kp(rad)', "actual": value})
value = (1.5 / 4)
assert math.isclose(value, 0.375, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=4의 포화 경계 오차 vmax/Kp(rad): 이득 두 배면 경계도 절반', "actual": value})
value = (1.5 / (4 * 0.5))
assert math.isclose(value, 0.75, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=4, 오차 0.5 rad에서 실제 초기 감소율을 선형 모델 예측으로 나눈 비율', "actual": value})
value = (2 * 1 - 1.5)
assert math.isclose(value, 0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '반례: 초기 오차 1 rad면 Kp=2도 한계를 넘는 양(rad/s)', "actual": value})
print(json.dumps(results, ensure_ascii=False))
