"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (10.1-10.0)
assert math.isclose(value, 0.1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '정상적인 0.1초 진행', "actual": value})
value = (0.1*2)
assert math.isclose(value, 0.2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '2배속 재생에서 실제 0.1초 동안 진행한 ROS 시간', "actual": value})
value = (12.0-12.0)
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '시뮬레이션 일시정지', "actual": value})
value = (9.0-12.0)
assert math.isclose(value, -3, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '로그 재생의 3초 역방향 점프', "actual": value})
value = (0.02*1)
assert math.isclose(value, 0.02, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '실시간 배율 1에서 지연 기반 단순 오차', "actual": value})
value = (0.02*2)
assert math.isclose(value, 0.04, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '실시간 배율 2에서 지연 기반 단순 오차', "actual": value})
value = (30.0-30.0)
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '정지 중 ROSTime 기반 timeout 누적', "actual": value})
value = (105.0-100.0)
assert math.isclose(value, 5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '같은 구간의 steady clock 기반 실제 경과', "actual": value})
print(json.dumps(results, ensure_ascii=False))
