"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (3.0 + 1.0)
assert math.isclose(value, 4, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Automatic: heartbeat 마지막 발행 3.0 s + lease 1.0 s = 노드 전체 publisher의 생존 만료 시각(s)', "actual": value})
value = (3.75 - 2.0)
assert math.isclose(value, 1.75, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '판정 시점 3.75 s에 카메라 토픽이 조용했던 시간(s): lease 1.0 s보다 길다', "actual": value})
value = ((3.0 + 1.0) - 3.75)
assert math.isclose(value, 0.25, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Automatic: 3.75 s 시점에 만료까지 남은 여유(s). 양수라서 카메라 publisher도 살아 있음으로 판정', "actual": value})
value = (3.75 - (2.0 + 1.0))
assert math.isclose(value, 0.75, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Manual by topic: 카메라 마지막 assert 2.0 s + lease 1.0 s 이후로 3.75 s 시점까지 지난 시간(s). 양수라서 liveliness lost 조건', "actual": value})
value = (0.5 - 1.0)
assert math.isclose(value, -0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'lease 호환성: 구독자 요청 0.5 s − 발행자 제공 1.0 s. 음수라서 연결 없음', "actual": value})
value = (2.0 - 1.0)
assert math.isclose(value, 1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'lease 호환성: 구독자 요청 2.0 s − 발행자 제공 1.0 s. 양수라서 호환', "actual": value})
value = (0.5 - 1 / 10)
assert math.isclose(value, 0.4, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '10 Hz 카메라 publisher에 lease 0.5 s를 걸 때 발행 주기 대비 여유(s)', "actual": value})
value = (1.0 - 1 / 1)
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '1 Hz heartbeat에 lease 1.0 s를 걸 때 여유(s): 0이라 경계에 걸림', "actual": value})
print(json.dumps(results, ensure_ascii=False))
