"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (125 - 124.5)
assert math.isclose(value, 0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '정상 dt: 124.5초 다음 125.0초 콜백 (s)', "actual": value})
value = (125 - 0)
assert math.isclose(value, 125, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '초기화 안 된 dt: 저장된 이전 시각 0, 첫 콜백 125.0초 (s)', "actual": value})
value = ((125 - 0) / (125 - 124.5))
assert math.isclose(value, 250, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '초기화 안 된 dt가 정상 dt의 몇 배인지', "actual": value})
value = (0.5 * (125 - 124.5))
assert math.isclose(value, 0.25, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '0.5 m/s로 적분한 정상 한 주기 이동거리 (m)', "actual": value})
value = (0.5 * (125 - 0))
assert math.isclose(value, 62.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '0.5 m/s로 적분한 첫 주기 이동거리, 초기화 안 된 dt 사용 (m)', "actual": value})
value = ((3.25 - 3) / (125 - 0))
assert math.isclose(value, 0.002, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '위치 차분 속도 추정: 3.0 m→3.25 m를 초기화 안 된 dt로 나눔 (m/s)', "actual": value})
value = ((125 - 0) - 2)
assert math.isclose(value, 123, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '2초 timeout 판정: 마지막 수신 시각이 0으로 기록된 경우 경과시간 - 한도 (s, 양수면 잘못 발동)', "actual": value})
value = (125.5 - 125)
assert math.isclose(value, 0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '가드 적용 후: 첫 샘플(125.0초)을 기준점으로만 저장하고 다음 125.5초 콜백의 dt (s)', "actual": value})
print(json.dumps(results, ensure_ascii=False))
