"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (10 * 1)
assert math.isclose(value, 10, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=10, 초기 오차 1 rad일 때의 초기 명령 속도(rad/s)', "actual": value})
value = ((10 * 1) / 2)
assert math.isclose(value, 5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=10 초기 명령이 최대 속도 2 rad/s의 몇 배인지', "actual": value})
value = (2 / 10)
assert math.isclose(value, 0.2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=10에서 포화가 풀리는 경계 오차 vmax/Kp(rad)', "actual": value})
value = ((1 - 0.2) / 2)
assert math.isclose(value, 0.4, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=10에서 1 rad부터 경계 0.2 rad까지 최대 속도로 이동하는 시간(s, 교육용 가정)', "actual": value})
value = (1 / 10)
assert math.isclose(value, 0.1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=10에서 선형 구간의 시간상수 1/Kp(s)', "actual": value})
value = (2 / 2)
assert math.isclose(value, 1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=2의 경계 오차: 초기 오차 1 rad와 같아 포화가 없는 경계 사례(rad)', "actual": value})
value = (1 / 2)
assert math.isclose(value, 0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=2의 시간상수(s)', "actual": value})
value = ((1 - 2 / 4) / 2)
assert math.isclose(value, 0.25, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=4에서 경계 오차 0.5 rad까지 최대 속도로 이동하는 시간(s, 교육용 가정)', "actual": value})
value = (10 * 0.1)
assert math.isclose(value, 1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '반례: Kp=10이라도 목표가 0.1 rad면 초기 명령 속도는 최대 속도보다 작다(rad/s)', "actual": value})
print(json.dumps(results, ensure_ascii=False))
