"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (8+8+8+8+25+8+8+9+9+9)
assert math.isclose(value, 100, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '흔들림 기록의 간격 10개 합(ms)', "actual": value})
value = ((8+8+8+8+25+8+8+9+9+9)/10)
assert math.isclose(value, 10, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '흔들림 기록의 평균 주기(ms) = 합 ÷ 간격 수', "actual": value})
value = (1000/10)
assert math.isclose(value, 100, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '평균 빈도(Hz) = 1000 ms ÷ 평균 주기 (균일한 기록도 같은 값)', "actual": value})
value = (15-10)
assert math.isclose(value, 5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '균일한 기록(모든 간격 10 ms)의 15 ms deadline 여유(ms)', "actual": value})
value = (15-8)
assert math.isclose(value, 7, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '흔들림 기록에서 보통 간격 8 ms의 여유(ms)', "actual": value})
value = (15-25)
assert math.isclose(value, -10, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '흔들림 기록에서 최대 간격 25 ms의 여유(ms): 음수면 마감을 넘김', "actual": value})
value = (25/10)
assert math.isclose(value, 2.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '최대 간격이 평균 주기의 몇 배인지', "actual": value})
value = (25*6/5-25)
assert math.isclose(value, 5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '제공 deadline을 최대 간격의 6/5배(30 ms)로 늘렸을 때 최대 간격의 여유(ms)', "actual": value})
value = (15-25*6/5)
assert math.isclose(value, -15, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": "그때 15 ms를 요청하던 구독자의 '요청 − 제공'(ms): 음수면 비호환", "actual": value})
print(json.dumps(results, ensure_ascii=False))
