"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (10 / 10)
assert math.isclose(value, 1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'RTF 기준: 시뮬레이션 10 s가 벽시계 10 s 동안 흐름', "actual": value})
value = (10 / 20)
assert math.isclose(value, 0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'RTF 반례: 같은 시뮬레이션 10 s가 벽시계 20 s 걸림', "actual": value})
value = (1000 / 100)
assert math.isclose(value, 10, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '100 Hz 루프의 주기(ms) = deadline 10 ms', "actual": value})
value = (10000 / 1000)
assert math.isclose(value, 10, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '1000 주기 동안 벽시계 10000 ms → 평균 간격(ms)', "actual": value})
value = ((1000 * 10) / 10000)
assert math.isclose(value, 1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '같은 실행의 RTF: 시뮬레이션 1000×10 ms ÷ 벽시계 10000 ms', "actual": value})
value = (25 - 10)
assert math.isclose(value, 15, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '그 실행에서 측정한 최대 간격 25 ms의 마감 초과량(ms)', "actual": value})
value = (3 / 1000 * 100)
assert math.isclose(value, 0.3, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '1000 주기 중 마감을 넘긴 3회의 비율(%)', "actual": value})
value = (10 / 0.5)
assert math.isclose(value, 20, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'RTF 0.5에서 시뮬레이션 10 ms 한 단계가 차지하는 벽시계 시간(ms)', "actual": value})
value = (25 - 20)
assert math.isclose(value, 5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'RTF 0.5 단계가 벽시계 예산 25 ms 안에 남기는 여유(ms, 양수면 충족)', "actual": value})
print(json.dumps(results, ensure_ascii=False))
