"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (2 * 1)
assert math.isclose(value, 2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=2, 초기 오차 1 rad의 명령 속도(한계와 같은 경계)', "actual": value})
value = (5 * 1)
assert math.isclose(value, 5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=5, 초기 오차 1 rad의 명령 속도', "actual": value})
value = (5 * 1 - 2)
assert math.isclose(value, 3, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=5 명령 속도가 vmax=2를 넘는 양', "actual": value})
value = (2 / 5)
assert math.isclose(value, 0.4, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=5에서 선형 모델이 성립하는 오차 한계 vmax/Kp', "actual": value})
value = (2 / 2)
assert math.isclose(value, 1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=2에서 선형 모델이 성립하는 오차 한계 vmax/Kp', "actual": value})
value = (1 / 5)
assert math.isclose(value, 0.2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=5 시간상수 1/Kp', "actual": value})
value = (1 / 2)
assert math.isclose(value, 0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=2 시간상수 1/Kp', "actual": value})
value = ((1 - 2 / 5) / 1)
assert math.isclose(value, 0.6, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=5, 초기 오차 1 rad 가운데 선형 구간 밖 비율', "actual": value})
value = (2 / 10)
assert math.isclose(value, 0.2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": 'Kp=10에서 선형 모델이 성립하는 오차 한계', "actual": value})
value = (0.5 / 5)
assert math.isclose(value, 0.1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '움직이는 목표 c=0.5, Kp=5의 정상상태 오차 c/Kp', "actual": value})
value = (5 * (0.5 / 5))
assert math.isclose(value, 0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '정상상태 명령 속도 Kp×(c/Kp)가 c=0.5와 같음(한계 안)', "actual": value})
value = (2.5 - 2)
assert math.isclose(value, 0.5, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '반례: 목표 속도 c=2.5가 vmax=2를 넘는 양(Kp와 무관)', "actual": value})
print(json.dumps(results, ensure_ascii=False))
