"""Purpose-built arithmetic checks; not robot or simulator execution."""
import math
import json
results = []
value = (0*0.3 + 0*0.1 + 1*2.0)
assert math.isclose(value, 2, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '정답 변환: 몸체 x_b(앞) = optical z_o, 0.3·0.1·2.0 중 2.0만 남음 (m)', "actual": value})
value = (0 - 1*0.3 + 0*0.1 + 0*2.0)
assert math.isclose(value, -0.3, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '정답 변환: 몸체 y_b(왼쪽) = -x_o, 오른쪽 0.3m는 y_b = -0.3 (m)', "actual": value})
value = (0*0.3 - 1*0.1 + 0*2.0)
assert math.isclose(value, -0.1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '정답 변환: 몸체 z_b(위) = -y_o, 아래 0.1m는 z_b = -0.1 (m)', "actual": value})
value = (2.0 - 0.3)
assert math.isclose(value, 1.7, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '흔한 실수: optical 좌표를 몸체 좌표에 그대로 복사하면 앞쪽 거리가 0.3m로 읽혀 실제 2.0m와 차이 (m)', "actual": value})
value = (0*(0*0 - 0*(0-1)) - 0*((0-1)*0 - 0*0) + 1*((0-1)*(0-1) - 0*0))
assert math.isclose(value, 1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '정답 행렬 M의 행렬식: +1이면 오른손 좌표계 유지', "actual": value})
value = (0*(0*1 - 0*0) - 0*((0-1)*1 - 0*0) + 1*((0-1)*1 - 0*0))
assert math.isclose(value, -1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '오답 A(z_b 부호만 빠뜨림)의 행렬식: -1이라 왼손 좌표계, REP-103 위반으로 검출됨', "actual": value})
value = (0*(0*0 - 0*1) - 0*(1*0 - 0*0) + 1*(1*1 - 0*0))
assert math.isclose(value, 1, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '오답 B(두 부호 모두 빠뜨린 순환 치환)의 행렬식: +1이라 행렬식 검사를 통과함', "actual": value})
value = (0.3 - (0 - 0.3))
assert math.isclose(value, 0.6, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '오답 B의 좌우 오류: 테스트 점에서 y_b가 +0.3(왼쪽)으로 나와 정답 -0.3과 차이 (m)', "actual": value})
value = ((0 - 1*0 + 0*0 + 0*2) - (1*0 + 0*0 + 0*2))
assert math.isclose(value, 0, rel_tol=1e-9, abs_tol=1e-9)
results.append({"name": '경계 사례: 정면 점 (0,0,2)에서 정답 y_b와 오답 B y_b의 차이는 0이라 오답이 드러나지 않음 (m)', "actual": value})
print(json.dumps(results, ensure_ascii=False))
